-- problem : https://school.programmers.co.kr/learn/courses/30/lessons/131123
-- 음식종류별로 즐겨찾기 수가 가장 많은 식당 조회
-- 조회 : 음식 종류, ID, 식당 이름, 즐겨찾기수
-- 정렬 : 음식 종류 DESC

SELECT A.FOOD_TYPE, REST_ID, REST_NAME, A.FAVORITES
FROM REST_INFO AS A
    JOIN (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) AS B
    ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE A.FAVORITES = B.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;


SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
    MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) AS MAX
    FROM REST_INFO
) AS A
WHERE FAVORITES = MAX
ORDER BY FOOD_TYPE DESC;